### ISSUE TITLE
Infinite loop when a task('s children) have it'self as a child

### ISSUE THREAD

**Issue by verpeteren** [thierry-f-78/pla#5]
I found this problem when I made a typo in the child number.

Here is a minimal test case that results in a infinite loop.

```
[1] bla
     child 1
````
But it turns out that the loop also occurs when there is further nesting

```
[1] bla
	child 2
[2] blabla
	child 3
[3] blablabla
	child 1
```

**Comment by thierry-f-78** [comment]
good catch ! it is fixed by commit 4a98415b90cabf75ea7a85d0f2fd289323677fef
